char *buf;
int token;
int tokenlen;
char tokenbuf[TOKENBUFLEN + 1];
char *scanptr;
char *tokenptr;
char *lineptr;
int addrmode;
int value;
int pass;
int where;
struct sym stab[26][NSYM];
int stack[STACKSIZE];
int stackindex;
int curloc;
int curlin;
int lstloc;
int cmp_count;
int err_count;
uint8_t *mem;
uint8_t *disk;
