void list(void);
int main(int argc, char *argv[]);
char * readfile(char *filename);
void scan_file(int k);
void scan_line(void);
struct sym * scan_add_symbol(void);
void scan_addr(void);
void scan_expr(void);
void scan_term(void);
void scan_factor(void);
void scan_error(char *errmsg);
struct sym * scan_lookup(void);
void scan_token(void);
void scan_branch(void);
void scan_value(void);
void scan_org(struct sym *p);
void scan_equ(struct sym *p);
void scan_bss(void);
void scan_ds(void);
void scan_asc(void);
void scan_dci(void);
void scan_byte(void);
void scan_word(void);
void scan_adc(void);
void scan_and(void);
void scan_asl(void);
void scan_bcc(void);
void scan_bcs(void);
void scan_beq(void);
void scan_bit(void);
void scan_bmi(void);
void scan_bne(void);
void scan_bpl(void);
void scan_brk(void);
void scan_bvc(void);
void scan_bvs(void);
void scan_clc(void);
void scan_cld(void);
void scan_cli(void);
void scan_clv(void);
void scan_cmp(void);
void scan_cpx(void);
void scan_cpy(void);
void scan_dec(void);
void scan_dex(void);
void scan_dey(void);
void scan_eor(void);
void scan_inc(void);
void scan_inx(void);
void scan_iny(void);
void scan_jmp(void);
void scan_jsr(void);
void scan_lda(void);
void scan_ldx(void);
void scan_ldy(void);
void scan_lsr(void);
void scan_nop(void);
void scan_ora(void);
void scan_pha(void);
void scan_php(void);
void scan_pla(void);
void scan_plp(void);
void scan_rol(void);
void scan_ror(void);
void scan_rti(void);
void scan_rts(void);
void scan_sbc(void);
void scan_sec(void);
void scan_sed(void);
void scan_sei(void);
void scan_sta(void);
void scan_stx(void);
void scan_sty(void);
void scan_tax(void);
void scan_tay(void);
void scan_tsx(void);
void scan_txa(void);
void scan_txs(void);
void scan_tya(void);
void scan_emit(int opcode, int count);
void scan_emit_byte(int byte);
void scan_emit_word(int word);
void stack_push(int value);
int stack_pop(void);
void stack_add(void);
void stack_sub(void);
void stack_neg(void);
void stack_mul(void);
void stack_div(void);
void stack_rem(void);
void stack_and(void);
void stack_or(void);
void stack_xor(void);
void stack_cpl(void);
void stack_shr(void);
void stack_shl(void);
void stack_lo(void);
void stack_hi(void);
